### ISSUE TITLE
baseVisitor[type] is not a function

### ISSUE THREAD

**Issue by fis-cz** [kesne/acorn-dynamic-import#13]
Hello,

I am trying to get this work with acorn 5.6.2 and I am getting error message (see subj.)

I am using:

```
const acorn = require("acorn-dynamic-import").default;
const walk = require("acorn-dynamic-import/lib/walk").default;
```

and it seems the AST is correctly build including the 
```
DynamicImportKey = 'Import';
```

but when the walker reaches the import it says that baseVisitior[type] is not a function (type = Import).

It seems that node type was not correctly registered to the walker.

When I check the contents of the walk.base, Import is still registered, but when I trace inside it disappears in this function:

Any ideas?

I just passed walk.base as to ancestor function:

```
walk.ancestor(program, { ...visitors... }, walk.base);
```

before it i called just 

```
walk.ancestor(program, { ...visitors... });
```

so default base was used.

**Comment by zmen** [comment]
I got the same error as well. It seems that the `inject` function return a new object with new keys but leaves the original `base` property alone.
I try to modify `node_modules/acorn-dynamic-import/lib/walk.js` like this then it works:

```javascript
function inject(injectableWalk) {
  // before
  //return Object.assign({}, injectableWalk, {
  //  base: Object.assign({}, injectableWalk.base, _defineProperty({}, _index.DynamicImportKey, function () {}))
  //});
  // after
  _defineProperty(injectableWalk.base, _index.DynamicImportKey, function () {})
  return injectableWalk
}
```
Since you've close this issue, may I ask that do you have a better solution?
